language: node_js
node_js:
  - "node"
  - "8"

before_install:
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn
  - yarn run setup

before_script:
  - greenkeeper-lockfile-update
  - yarn test

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - yarn coverage
