service: flickr-wormhole

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 1337
  webpackIncludeModules: true

functions:
  api:
    handler: src/index.server
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true
  playground:
      handler: src/index.playground
      events:
        - http:
            path: "/playground"
            method: get
            cors: true
