import Flickr from "@/flickr"

export default async function search(
  { apiKey = Flickr.apiKey } = {},
  {
    userId = ``,
    tags = ``,
    tagMode = `any`,
    text = ``,
    minUploadDate = ``,
    maxUploadDate = ``,
    minTakenDate = ``,
    maxTakenDate = ``,
    license = ``,
    privacyFilter = 0,
    bbox = ``,
    accuracy = ``,
    safeSearch = 0,
    contentType = 0,
    machineTags = ``,
    machineTagsMode = `any`,
    groupId = ``,
    contacts = ``,
    woeId = ``,
    placeId = ``,
    media = `all`,
    hasGeo = 0,
    geoContext = 0,
    lat = ``,
    lon = ``,
    radius = ``,
    radiusUnits = ``,
    isCommons = false,
    inGallery = false,
    isGetty = false,
    extras = ``,
    page = 1,
    perPage = 100,
    sort = ``
  } = {}
) {
  return await Flickr.fetchResource(
    `flickr.photos.search`,
    { apiKey },
    {
      userId,
      tags,
      tagMode,
      text,
      minUploadDate,
      maxUploadDate,
      minTakenDate,
      maxTakenDate,
      license,
      privacyFilter,
      bbox,
      accuracy,
      safeSearch,
      contentType,
      machineTags,
      machineTagsMode,
      groupId,
      contacts,
      woeId,
      placeId,
      media,
      hasGeo,
      geoContext,
      lat,
      lon,
      radius,
      radiusUnits,
      isCommons,
      inGallery,
      isGetty,
      extras,
      page,
      perPage,
      sort
    }
  )
}
